### ISSUE TITLE
es6 import of a language file does not work

### ISSUE THREAD

**Issue by axten** [brightcove/videojs-errors#115]
## Description
if I try to import a language file I got ReferenceError: videojs is not defined

so any lang file should have an import statement befor videojs to fix this.
besides that, a work around could be to provide the pure json files in videojs build.
this also would be great to extend a language during project build.

## Steps to reproduce
just do 
```
import videojs from 'video.js';
import 'videojs-errors';

import 'videojs-errors/dist/lang/de';
```

### Expected
should work as expected

### Actual
it breaks 

## Additional Information
videojs: 6.8.0

**Comment by axten** [comment]
no, the lang folder is not included in dist package.

**Comment by gkatsev** [comment]
lang folder is now included in the dist folder. Both a .js and a .json file are available there.
