### ISSUE TITLE
HLS Live Playback not satisfying timeout and pauses after 45 seconds.

### ISSUE THREAD

**Issue by daveferrara1** [brightcove/videojs-errors#132]
## Description
Briefly describe the issue.
When we cast our stream (chromecast). 
If we have included the errors plugin, the timeout is not satisfied for live HLS content.
The plugin is calling triggerReady(). Thats call seems to cause the problem if we pause on a break before that, the timeout is not started.

Looking to know how I could prevent thet timeout, reset it, or satisfy it.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Include this plugin 
2. include this plugin and view issue: https://github.com/silvermine/videojs-chromecast/issues/28

### Expected
Video cast as normal: 'vjs-is-waiting' or stall to stop. 

### Actual
Videois casts and pauses after 45 seconds.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:

#### videojs
what version of videojs does this occur with?
"version": "6.12.1",

Can reproduce here: https://dev.pac-12.com/live/pac-12-live-press-conferences

**Comment by daveferrara1** [comment]
https://github.com/brightcove/videojs-errors/pull/134

**Comment by daveferrara1** [comment]
For LIVE HLS playback - the player.currentTime() call inside onPlayStartMonitor() returns 0 and the times out. The current time in our case is in the remote player. PR above creates a config to ignore the monitoring should one choose.

Inside a custom plugin we simply use:

```this.player.errors({
        ignorePlayStartMonitor: this.isCasting(),
        errors: OurCustomErrorsObject
      });```

**Comment by gkatsev** [comment]
you can now set `timeout: Infinity` to handle this. Sorry it's taken so long, though, I expect you've been using your fork in the meanwhile.
