### ISSUE TITLE
Disabling default error message(s)

### ISSUE THREAD

**Issue by thijstriemstra** [brightcove/videojs-errors#21]
I'm working on a plugin that allows you to [record audio/video using video.js](https://github.com/collab-project/videojs-record). When the user requests access to the system's microphone using `getUserMedia` there's a chance he denies access and this throws an error message. I'd like to use your plugin for this but running into a problem;

when loading the plugin it immediately shows a `PLAYER_ERR_NO_SRC` error. This is expected because you're working without a source when recording locally. Is there a way to disable this error message (or all of them)?

**Comment by dmlap** [comment]
I would have assumed `getUserMedia` would count as a valid source. Is there any way to detect user media has been assigned to the player?

**Comment by thijstriemstra** [comment]
Basically it starts with the player displaying nothing but a large button that, once clicked, will launch the microphone/webcam browser-dialog using `getUserMedia`. Once that's done it assigns the stream to the player's src, as you can see [here](https://github.com/collab-project/videojs-record/blob/master/src/js/videojs.record.js#L182) and [here](https://github.com/collab-project/videojs-record/blob/master/src/js/videojs.record.js#L448).

I tried testing the `videojs-errors` plugin by adding an `errors` entry to `plugins` [here](https://github.com/collab-project/videojs-record/blob/master/examples/video-only.html#L44) for example but this displays the `PLAYER_ERR_NO_SRC` error immediately since there's no `src` value available at startup, I control that in a different way. Since that plugin makes quite a few of these adjustments to the default flow of the video.js player, I expect I won't need most of the error messages that `videojs-errors` provides but provide my own custom ones instead.

**Comment by gkatsev** [comment]
It's possible it needs to be fixed at the videojs level itself rather than in this plugin. Also, you might be able to clear the error via `player.error()` after listening to the error event.

**Comment by thijstriemstra** [comment]
Thanks for the feedback. How does one clear a specific error via `player.error()`? I've tried stopping the event but it gives strange results in the UI:

```javascript
this.player().on('error', function(e) {
    console.log(e);
    e.stopImmediatePropagation();
    var error = this.player().error();
    console.log('error!', error.code, error.type);
});
```
Also looks like the `error` event isn't documented at all for player.

**Comment by gkatsev** [comment]
If it's undocumented, it's probably an oversight. You can call `Player#error` with `null` to reset any errors: https://github.com/videojs/video.js/blob/master/src/js/player.js#L1440

**Comment by thijstriemstra** [comment]
Thanks, opened a ticket for the [missing event docs](https://github.com/videojs/video.js/issues/1810). I tried using `player.error(null)` before with:

```javascript
player.on('error', function()
{
    player.error(null);
    console.log('player error:', player.error());
});
```
but got this error:
```
TypeError: this.da is null
http://vjs.zencdn.net/4.11.3/video.js
Line 78
```
which translates to:

```
TypeError: this.error_ is null
http://localhost:8080/video.js/dist/video-js/video.dev.js
Line 5058
```
Something in this line:

```javascript
vjs.log.error('(CODE:'+this.error_.code+' '+vjs.MediaError.errorTypes[this.error...
```

Any ideas?

**Comment by dev-interactive-video** [comment]
Yeah, would be nice to be able to catch all player errors and disable the default behavior. Maybe it is already possible? Just read the source code but didn't find any way to do it.

**Comment by gkatsev** [comment]
It's been a while, is the outcome here to make sure that `player.error(null)` is documented?
